site:
  name: '惠州市富利源实业有限公司'
  site: 'http://8.163.120.238:81'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false

metadata:
  title:
    default: '惠州市富利源实业有限公司'
    template: '%s — 惠州市富利源实业有限公司'
  description: '惠州市富利源实业有限公司专注塑料薄膜制造机设备，主要产品包括 PVC 薄膜机、PE 保鲜膜机、拉伸膜机等。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: '惠州市富利源实业有限公司'
    images:
      - url: '~/assets/images/default.png' # 替换为你自己的默认分享图片
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: zh
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # 博客文章链接格式，可保持
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # 博客列表页路径，可改为 'news' 或 '文章'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # 分类路径，可改为 '分类'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # 标签路径，可改为 '标签'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # 可替换为百度统计等其他工具的ID

ui:
  theme: 'system' # 可选: "system" | "light" | "dark" | "light:only" | "dark:only"
